'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace App_UNAD.App

    Partial Public Class Student
        Public Property StudentId As Integer
        Public Property Email As String
        Public Property Document As String
        Public Property Password As String
    
    End Class

End Namespace
